language: c

dist: trusty
sudo: false

env:
  global:
  - CFLAGS="-O2 -g3 -std=c99 -Wall -Wextra -fvisibility=hidden -fno-strict-aliasing -Wno-unused-parameter"
  - CPPFLAGS="-D_DEFAULT_SOURCE"

addons:
  apt:
    packages:
    - valgrind
    - libev-dev

compiler:
  - gcc
  - clang

script:
  - make
