language: c

dist: trusty
sudo: false

env:
  global:
  - CFLAGS="-O2 -g3 -std=c99 -Wall -Wextra -fvisibility=hidden -fno-strict-aliasing -Wno-unused-parameter"
  - CPPFLAGS="-D_DEFAULT_SOURCE"

addons:
  apt:
    packages:
    - valgrind
    - libev-dev
    - git-buildpackage
    - dh-apparmor
    - devscripts
    - debhelper

compiler:
  - gcc
  - clang

script:
  - make
  - gbp buildpackage --git-verbose --git-notify=off --git-verbose --git-ignore-branch --git-notify=off --git-force-create -i -us -uc -S -sa
  - gbp buildpackage --git-verbose --git-notify=off --git-verbose --git-ignore-branch --git-notify=off --git-force-create -i -us -uc -b
